global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'flink_jobmanager'
    static_configs:
      - targets: ['jobmanager:9249']

  - job_name: 'flink_taskmanager'
    static_configs:
      - targets: ['taskmanager:9249']